### PR TITLE
fix GEARPUMP-187 update site to 0.8.1

### PR DESCRIPTION
**Pull request by kkasravi**

### CODE REVIEW

**Comment by manuzhang** [comment]
@kkasravi We need to update version number in `_config.yml` as well

**Comment by manuzhang** [comment]
+1

**Comment by manuzhang** [comment]
The pr is already merged but not synced from https://git-wip-us.apache.org/repos/asf?p=incubator-gearpump-site.git;a=log;h=refs/heads/asf-site

**Comment by kkasravi** [comment]
@manuzhang does sync happen automatically?

**Comment by manuzhang** [comment]
should be. I'm going to create an infra jira for the issue.

**Comment by manuzhang** [comment]
created https://issues.apache.org/jira/browse/INFRA-12423

**Pull request closed without merging**
